### ISSUE TITLE
Final Assignments: User Manual, Video, Buildversion

### ISSUE THREAD

**Issue by RVoelkel** [UniRegensburg/ASE_WS1718-sprechstundenverwaltung#91]
**Das müssen Sie am 21. April einreichen:**

- [x] Den vollständigen Quellcode Ihrer Software mit allen Assets, die zur Erstellung 
notwendig sind (RELEASE auf Github?!) 
- [x] Eine Kurzbeschreibung des Projekts [Readme.md] mit den wichtigsten Zielen und 
Funktionen sowie den Namen und Email-Adressen aller Beteiligten
- [x] Eine vollständige Anleitung zur Inbetriebnahme der Software auf Basis des 
Repositories [Readme.md]
- [x] Ein vollständiges User Manual, das die wichtigsten Funktionen Ihrer Anwendung – mit unterstützenden Screenshots – vorstellt und erklärt [docs/Manual.md]
- [x] Ein kurzes Video (max. 5min, MP4, 1080p), das die wichtigsten Funktionen der Anwendung vorstellt [docs/intro.mp4]
- [ ] Desktop-Anwendungen: Eine installier- bzw. ausführbare Version Ihrer Software für Windows-Rechner [build/]
- [x] Web-Anwendungen: Einen Link zu einer gehosteten, benutzbaren Version Ihrer Software [Readme.md] (ggf. mit Demo-Accounts)

Die Abgabe aller Artefakte erfolgt über einen finalen Release in Ihrem Github-Repository.
